name: Test

on:
  push:
    branches:
      - master
      - ci/*
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Test ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --release
        env:
          RUST_BACKTRACE: "1"

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --release
        env:
          RUST_BACKTRACE: "1"

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Setup Tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --no-fail-fast --all-features --out xml

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: cobertura.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml
